### ISSUE TITLE
Confusing dates on HTML version of CV

### ISSUE THREAD

**Issue by kaoru** [charlesdebarros/My-Blog#30]
Hi Charles,

I was just looking at your CV on https://charlesdebarros.herokuapp.com/welcome/cv and the dates in the "EDUCATION AND IT TRAINING" section are confusing... what format are they in?

https://github.com/charlesdebarros/My-Blog/blob/63e2cd65d2274bb059617a62262b6aae8417e243/app/views/welcome/cv.html.erb#L87

```
<h3>02/88-12/91 - Henrique Lage Industrial & Technology School, RJ, Brazil -> Diploma in Engineering and Architectural drawing</h3>
```

Ok so that looks like `MM/YY` right? February 1988 to December 1991?

So what is this:

```
17/02-09/05 - Makers Academy, London -> Web/Software Junior Development
```

The 17th month of 2002? 🤯 My best guess is that you wrote those dates _in 2014_ and your internal algorithm was:

```
class Date
  def to_s
    if self.year == Date.today.year
      strftime("%d/%m")
    else
      strftime("%m/%y")
    end
  end
end
```

Is that what happened? 😅

**Comment by charlesdebarros** [comment]
> Hi Charles,
> 
> I was just looking at your CV on https://charlesdebarros.herokuapp.com/welcome/cv and the dates in the "EDUCATION AND IT TRAINING" section are confusing... what format are they in?
> 
> https://github.com/charlesdebarros/My-Blog/blob/63e2cd65d2274bb059617a62262b6aae8417e243/app/views/welcome/cv.html.erb#L87
> 
> ```
> <h3>02/88-12/91 - Henrique Lage Industrial & Technology School, RJ, Brazil -> Diploma in Engineering and Architectural drawing</h3>
> ```
> 
> Ok so that looks like `MM/YY` right? February 1988 to December 1991?
> 
> So what is this:
> 
> ```
> 17/02-09/05 - Makers Academy, London -> Web/Software Junior Development
> ```
> 
> The 17th month of 2002? 🤯 My best guess is that you wrote those dates _in 2014_ and your internal algorithm was:
> 
> ```
> class Date
>   def to_s
>     if self.year == Date.today.year
>       strftime("%d/%m")
>     else
>       strftime("%m/%y")
>     end
>   end
> end
> ```
> 
> Is that what happened? 😅

Well spotted. 

Actually, it was supposed to be 17/02/14 to 09/05/14! How did I miss that!!!

The code is corret but me,  and this is what happens when you try to be too smart, mixed dd/mm with mm/yy in the Education section. The problem was in between the chair and the keyboard! 😂

That has now been fixed.

Thank you for the heads-up. 😉

Charles
